### PR TITLE
Changes to run v1.5 directly from Maven Central

### PR DESCRIPTION
**Pull request by betoboullosa**
Dear @bwaldvogel , DKPro (https://github.com/dkpro/dkpro-core) has a dependency on liblinear 1.5, and we would like to have that dependency downloaded directly from Maven Central (currently, only versions >=1.8 of liblinear are kept there). We need to keep the old group id/artifact id though (liblinear.liblinear). 

I provided the changes needed for packaging a 1.51 version without the need of other dependencies apart from the ones already in Maven Central.

Please, would it be possible for you to incorporate those changes to your repository and uploading the new jar to Maven Central?

Thank you,
Beto

--------
These changes are needed to upload v.1.5 to Maven Central:

* Use netlib-java 0.9.3 dependency from Maven Central, instead of using BLAS 0.8 with manual dependency resolution.
* Updates to Tron.java due to newer BLAS version in netlib-java 0.9.3
* Updates in the pom.xml (maybe some extra configuration is needed)

### CODE REVIEW

**Comment by bwaldvogel** [comment]
Why is upgrading to latest liblinear-java not an option?

**Comment by betoboullosa** [comment]
Actually, we have a transitive dependency, DKPro uses a third-party module that, by it's turn, depends on liblinear 1.5. Thus, to upgrade to the the latest liblinear, we would have to fork that third-party module, something that we'd prefer not to do.

**Comment by betoboullosa** [comment]
Hi, @bwaldvogel , do you think you will be able to integrate the changes and upload the updated version to maven central?

**Comment by bwaldvogel** [comment]
Couldn’t you overwrite the version of liblinear that gets pulled in? With your proposed patch you would need to force version 1.51 over 1.5 anyway.

**Comment by betoboullosa** [comment]
Yes, that would be fine for us. I've updated the pom.xlm to 1.5.

**Comment by betoboullosa** [comment]
With that change would it be ok for you uploading 1.5 to Maven Central then?

**Comment by bwaldvogel** [comment]
Actually I meant the latest version: 1.95.

**Comment by betoboullosa** [comment]
The problem is, we intend to bundle and upload to Maven Central the third party module that uses liblinear. And, since liblinear group id changed between 1.5 and 1.95, we'd have to change the source code from that third party module in order to support that, something we want to avoid (that third party project is frozen in Google Code). At the other hand, if liblinear 1.5 is present in Maven Central with the original group id, we'll only have to update the third party module pom (to use liblinear 1.5 instead of 1.51 - no source code changes) when we bundle it.

**Comment by bwaldvogel** [comment]
I’ve started [branch 1.7](1.7|https://github.com/bwaldvogel/liblinear-java/tree/1.) that could be released as version 1.7.1. Please note that I cannot release to Maven central with groupId `liblinear`. However, version 1.7.1 would live in the (old) Java package `liblinear` and has **no dependencies** to other libraries such as BLAS.
Could you test the temporary snapshot [liblinear-1.7.1-SNAPSHOT.jar](http://www.bwaldvogel.de/liblinear-java/liblinear-1.7.1-SNAPSHOT.jar) if it would be working for you?

**Comment by betoboullosa** [comment]
I tested the 1.7.1 snapshot that you provided, it seems to work fine. Please, go ahead with the release.  :)

**Comment by bwaldvogel** [comment]
Released version 1.7.1.

**Comment by betoboullosa** [comment]
Thank you, @bwaldvogel !

**Pull request closed without merging**
