### PR TITLE
fixed  the code in Linear.java to take the max_iter from input when using L2R_L2LOSS_SVC or L2R_LR as solver

### PR DESCRIPTION
**Pull request by salimm**
Previously, when one uses the constructor for Parameter to set max_iter the code wouldn't use it when using either L2RL2LLOSS_SVC or L2R_LR. I changed the code to allow it to receive the max_iter from parameter when set.

### CODE REVIEW

**Comment by bwaldvogel** [comment]
Thanks for your contribution.
I would like to merge your changes, but it is very hard for me to grasp the real change you made from looking at the diff. It appears that you also changed the formatting of the file.

I would appreciate it very much if you could resubmit the pull request with less formatting changes.

**Comment by salimm** [comment]
Dear Benedikt,

I guess I accidentally used auto formatter in Eclipse. I will create a new
branch. The changes are very small I can redo the whole thing.

Thanks,
Salim

**Comment by salimm** [comment]
Dear Benedikt,

I just created a new fork of the project and made a new pull request with
the changes. I also fixed it for other solvers.

Thanks,
Salim

**Comment by bwaldvogel** [comment]
I’m sorry but I cannot find your new pull request.

**Comment by salimm** [comment]
Sorry, I just made the pull request again

**Comment by salimm** [comment]
Its a separate pull request

**Pull request closed without merging**
